
module kern_texture

  implicit none
  real, pointer, texture, dimension(:) :: a_Tex => null()
  
  contains

  ! a is shorter in size, and a_Tex is larger
  attributes(global) subroutine stride_texture(a, jump)
    real :: a(:)
    integer, value, intent(in) :: jump
    integer :: i, is

    i = blockDim%x * (blockIdx%x - 1) + threadIdx%x 
    is = i * jump
    a(i) = a_Tex(is) + 1

  end subroutine stride_texture

end module kern_texture
